[target.riscv64gc-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "riscv64-linux-musl-cc"

[target.loongarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "loongarch64-linux-musl-cc"
